# Definoni backend-in dhe frontend-in

[builds]
  [[builds.backend]]
    type = "python"
    path = "backend"    # Vendosni këtu folderin backend
    start = "python app.py"

  [[builds.frontend]]
    type = "nodejs"
    path = "frontend"   # Vendosni këtu folderin frontend
    start = "npm start"
