# Railway Configuration file

# Tregon se ky është një projekt që përdor Docker
[build]
  # Path për Dockerfile për backend
  backend = "backend/Dockerfile"
  # Path për Dockerfile për frontend
  frontend = "frontend/Dockerfile"

# Të dhëna të tjera të konfigurimit për Railway

[services]
  [[services.backend]]
  # Emri i shërbimit backend (Python Flask)
  name = "backend"
  # Porti që do të ekspozohet për backend
  port = 5000

  [[services.frontend]]
  # Emri i shërbimit frontend (React)
  name = "frontend"
  # Porti që do të ekspozohet për frontend
  port = 3000
